### ISSUE TITLE
Sheep Killing

### ISSUE THREAD

**Issue by myxxmikeyxx** [TheOnlyTails/RubyMod#48]
I noticed that when you shear a sheep and then kill it, it always drops a ruby wool block.
This might need to be changed and I believe you can change it in the loot tables and chances/conditions unless you did the drop through code then maybe do a check if sheep is sheared or not and if not then drop random amount between X and Y.

**Comment by TheOnlyTails** [comment]
@myxxmikeyxx Can you check if that happens with regular sheep too?

**Comment by myxxmikeyxx** [comment]
In creative I spawned 5 sheep, sheared them, then killed them.  They did not drop any wool.
I did the same to your ruby sheep and it dropped a ruby wool block every time. I fell its something with your loot tables and it needs the condition for if its already sheared.

(P.S.) What made you code in Kotlin and where did you learn it?

**Comment by TheOnlyTails** [comment]
From what I see, the loot tables for regular sheep and my ruby sheep are identical, and nothing in `SheepEntity` shows any sign of a loot table being modified via code.

Regarding how I learned Kotlin, I thought it was a cool language, learned it [here](https://www.coursera.org/learn/kotlin-for-java-developers) and fell in love with it.

**Comment by myxxmikeyxx** [comment]
That’s strange then that it is working differently. If I find anything I’ll let you know but I’m just starting out and not well versed.
